---
title: "cBioPortalData Studies"
author:
  - name: Marcel Ramos
    affiliation: CUNY School of Public Health, New York, NY
vignette: >
  %\VignetteIndexEntry{cBioPortal Studies}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  html_document:
    mathjax: null
---

# Available Studies by function

## cBioPortalData()

These studies are available through the cBioPortal API, i.e., `cBioPortalData`
function.

### NOTES

*  This list is different from those studies available via the `cBioDataPack`
function.

* Scroll to the right for more information (esp. for the `studyId` column)

```{r,echo=FALSE,message=FALSE,warn=FALSE}
library(cBioPortalData)
library(knitr)
cbio <- cBioPortal()
knitr::kable(getStudies(cbio), align = "l", escape = FALSE, format = "html",
    caption = "List of available studies from cBioPortalData API") %>%
    kableExtra::kable_styling(
        bootstrap_options = c("hover", "striped", "responsive"),
        full_width = FALSE
    )
```

## cBioDataPack()

```{r,echo=FALSE}
data("studiesTable")
studiesTable$URL <- vapply(studiesTable$URL, paste, character(1L), collapse = ", ")
library(tibble)
studiesTable <- as_tibble(studiesTable)
knitr::kable(studiesTable, align = "l", escape = FALSE, format = "html",
    caption = "List of available packaged studies in cBioDataPack") %>%
    kableExtra::kable_styling(
        bootstrap_options = c("hover", "striped", "responsive"),
        full_width = FALSE
    )
```

