name: MAE Workshop Check

on:
  pull_request:
  push:
    paths:
      - 'DESCRIPTION'
      - '**.yaml'
    branches:
      - devel

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: TRUE
  R_REMOTES_STANDALONE: TRUE
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  CRAN: https://p3m.dev/cran/__linux__/noble/latest
  BIOC_RELEASE: RELEASE_3_21

jobs:
  check:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_21

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Query dependencies
        run: |
          BiocManager::install(c("remotes", "rcmdcheck"))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-r-${{ env.BIOC_RELEASE }}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ env.BIOC_RELEASE }}-

      - name: Install Package Dependencies
        run: |
          remotes::install_local(dependencies = TRUE, repos = BiocManager::repositories(), build_vignettes = TRUE, upgrade = TRUE)
          BiocManager::install(update = TRUE, ask = FALSE)
        shell: Rscript {0}

      - name: Check Package
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}

      - name: Build pkgdown
        if: github.event_name != 'pull_request'
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'pkgdown::build_site()'

      - name: Upload pkgdown artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: check
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        id: deployment
        uses: actions/deploy-pages@v4

  img-push:
    needs: check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/devel'
    env:
      REGISTRY: ghcr.io
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Register repo name
        if: github.event_name != 'pull_request'
        id: reg_repo_name
        run: |
          echo CONT_IMG_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: >
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CONT_IMG_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CONT_IMG_NAME }}:devel
